services:
  nextjs:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile  # Указываем правильный путь
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    volumes:
      - ./upload:/app/upload